config/routes.rb
Pages::Application.routes.draw do

  namespace :admin do resources :field_values end

  devise_for :users

  

  namespace :admin do 
    
    
    match 'settings' => 'settings#categories'
    match 'settings/categories' => 'settings#categories'
    match 'settings/fields' => 'settings#fields'
    
    resources :field_types
    resources :assets, :only => [ :create, :destroy ]
    resources :themes, :only => [ :index, :show  ]
    resources :agencies
    resources :items
    resources :categories, :only => [ :new, :create, :destroy ]
    resources :fields
    resources :components, :except  => [ :index, :show ]
  end
  
  match '/admin' => 'admin/settings#fields'
  
  match ':permalink' => 'sites#show'
  
  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin/field.rb
class Admin::Field < ActiveRecord::Base
  belongs_to :category
  belongs_to :field_type
    
  validates_presence_of :category, :field_type
    
  default_scope :order => 'label asc'
  
  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
end

app/models/admin/field_type.rb
class Admin::FieldType < ActiveRecord::Base
  attr_accessible :label
  belongs_to :agency  
  has_many :fields
  
  default_scope :order => 'label asc'
end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < ApplicationController

  before_filter :authenticate_user!

  # GET /admin/fields
  # GET /admin/fields.json
  def index
    @admin_fields = Admin::Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_fields }
    end
  end

  # GET /admin/fields/1
  # GET /admin/fields/1.json
  def show
    @admin_field = Admin::Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_field }
    end
  end

  # GET /admin/fields/new
  # GET /admin/fields/new.json
  def new
    @field = Admin::Field.new(:category => Admin::Category.new, :field_type => Admin::FieldType.new)
    @categories = @current_agency.categories
    @fieldtypes = @current_agency.field_types

    respond_to do |format|
      format.html { render :partial => 'new_field' }
      format.json { render json: @field }
    end
  end

  # GET /admin/fields/1/edit
  def edit
    @admin_field = Admin::Field.find(params[:id])
  end

  # POST /admin/fields
  # POST /admin/fields.json
  def create
    @admin_field = Admin::Field.new(params[:admin_field])

    respond_to do |format|
      if @admin_field.save
        format.html { 
          @categories = @current_agency.categories
          @fields = @categories.map{|c| c.fields}.flatten.sort{|x,y| x.label <=> y.label}
          @fieldtypes = @current_agency.field_types
          render :partial => 'admin/fields/field', :collection => @fields  
        }
        format.json { render json: @admin_field, status: :created, location: @admin_field }
      else
        format.html { 
          render json: @admin_field.errors, status: :unprocessable_entity }
        format.json { 
          render json: @admin_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/fields/1
  # PUT /admin/fields/1.json
  def update
    @admin_field = Admin::Field.find(params[:id])

    respond_to do |format|
      if @admin_field.update_attributes(params[:admin_field])
        format.html { redirect_to @admin_field, notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/fields/1
  # DELETE /admin/fields/1.json
  def destroy
    @admin_field = Admin::Field.find(params[:id])
    @admin_field.destroy

    respond_to do |format|
      format.html { redirect_to admin_fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/fields_helper.rb
module Admin::FieldsHelper
end

app/views/admin/fields/_field.html.erb
<tr>
  <td><%= field.label %></td>
  <td>
    <%= form_for field, :remote => true, :format => :json, :html => { :class => "slim change-category" } do |f| %>
      <%= f.collection_select :category_id, @categories, :id, :label, :prompt => true,   %>
      <%= f.submit :style => 'display:none', :class => 'submit' %>
    <% end %>
  </td>
  <td>
    <%= form_for field, :remote => true, :format => :json, :html => { :class => "slim change-fieldtype" } do |f| %>
      <%= f.collection_select :field_type_id, @fieldtypes, :id, :label, :prompt => true,   %>
      <%= f.submit :style => 'display:none', :class => 'submit' %>
    <% end %>
  </td>
  <td><%= link_to 'Delete', field, :remote => true, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini delete-button' %></td>
</tr>

app/views/admin/fields/_field_input.html.erb
<% if field.field_type_id == 1 %>
    <%= text_field_tag :fieldvalue, fieldvalue.value %>
<% elsif field.field_type_id == 2 %>
<select/>
<% elsif field.field_type_id == 3 %>
<input type="checkbox">
<% end %>

app/views/admin/fields/_field_input_empty.html.erb
<% if field.field_type_id == 1 %>
  <%= text_field_tag "item[field][#{field.id}]", nil, :class => 'span12' %>
<% elsif field.field_type_id == 2 %>
<select/>
<% elsif field.field_type_id == 3 %>
  <%= check_box_tag "item[field][#{field.id}]", true %>
<% end %>

app/views/admin/fields/_field_input_with_value.html.erb
<% 
    field_value = Admin::FieldValue.where(:item_id => item_id, :field_id => field.id).first 
    value = field_value.value unless field_value.nil?
%>
<% if field.field_type_id == 1 %>
    
    <%= text_field_tag "item[field][#{field.id}]", value %>
<% elsif field.field_type_id == 2 %>
<select/>
<% elsif field.field_type_id == 3 %>
  <%= check_box_tag "item[field][#{field.id}]", true %>
<% end %>

app/views/admin/fields/_form.html.erb
<%= form_for(@admin_field) do |f| %>
  <% if @admin_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_field.errors.count, "error") %> prohibited this admin_field from being saved:</h2>
      <ul>
      <% @admin_field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/fields/_new_field.html.erb
<%= form_for(@field, :remote => true, :html => {:'data-type' => 'html'} ) do |f| %>
<div class="row">
  <div class="span3">
    <%= f.label :label %>
    <%= f.text_field :label, :class => 'new-field-label' %></td>
  </div>
  <div class="span3">
      <%= f.label :category_id, 'Category' %>
      <%= f.collection_select :category_id, @categories, :id, :label, :prompt => true,   %>
  </div>
  <div class="span2">
      <%= f.label :category_id, 'Type' %>
      <%= f.collection_select :field_type_id, @fieldtypes, :id, :label, :prompt => true,   %>
  </div>
</div>
<div class="row">
  <div class="span3">
    <%= f.submit 'Create', :class => 'btn btn-primary btn-small'  %>
    <%= button_tag 'Cancel', :class => 'btn btn-danger btn-small cancel-new-field'  %>
  </div>
</div>
<% end %>

app/views/admin/fields/edit.html.erb
<h1>Editing admin_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_field %> |
<%= link_to 'Back', admin_fields_path %>

app/views/admin/fields/index.html.erb
<h1>Listing admin_fields</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Active</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_fields.each do |admin_field| %>
  <tr>
    <td><%= admin_field.label %></td>
    <td><%= admin_field.active %></td>
    <td><%= admin_field.category_id %></td>
    <td><%= link_to 'Show', admin_field %></td>
    <td><%= link_to 'Edit', edit_admin_field_path(admin_field) %></td>
    <td><%= link_to 'Destroy', admin_field, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field', new_admin_field_path %>

app/views/admin/fields/new.html.erb
<h1>New admin_field</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_fields_path %>

app/views/admin/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @admin_field.label %>
</p>

<p>
  <b>Active:</b>
  <%= @admin_field.active %>
</p>

<p>
  <b>Category:</b>
  <%= @admin_field.category_id %>
</p>


<%= link_to 'Edit', edit_admin_field_path(@admin_field) %> |
<%= link_to 'Back', admin_fields_path %>