config/routes.rb
Pages::Application.routes.draw do

  namespace :admin do resources :field_values end

  devise_for :users

  

  namespace :admin do 
    
    
    match 'settings' => 'settings#categories'
    match 'settings/categories' => 'settings#categories'
    match 'settings/fields' => 'settings#fields'
    
    resources :field_types
    resources :assets, :only => [ :create, :destroy ]
    resources :themes, :only => [ :index, :show  ]
    resources :agencies
    resources :items
    resources :categories, :only => [ :new, :create, :destroy ]
    resources :fields
    resources :components, :except  => [ :index, :show ]
  end
  
  match '/admin' => 'admin/settings#fields'
  
  match ':permalink' => 'sites#show'
  
  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin/field_value.rb
class Admin::FieldValue < ActiveRecord::Base
  attr_accessible :field_id, :item_id, :value
  
  belongs_to :item
  belongs_to :field
  
  delegate :field_type_id, :label, :category, :to => :field
  
  scope :find_by_item_and_field_ids, lambda { |item_id, field_id| where(:item_id => item_id, :field_id => field_id).pluck(:value).first}
end

app/controllers/admin/field_values_controller.rb
class Admin::FieldValuesController < ApplicationController
  # GET /admin/field_values
  # GET /admin/field_values.json
  def index
    @admin_field_values = Admin::FieldValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_field_values }
    end
  end

  # GET /admin/field_values/1
  # GET /admin/field_values/1.json
  def show
    @admin_field_value = Admin::FieldValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_field_value }
    end
  end

  # GET /admin/field_values/new
  # GET /admin/field_values/new.json
  def new
    @admin_field_value = Admin::FieldValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_field_value }
    end
  end

  # GET /admin/field_values/1/edit
  def edit
    @admin_field_value = Admin::FieldValue.find(params[:id])
  end

  # POST /admin/field_values
  # POST /admin/field_values.json
  def create
    @admin_field_value = Admin::FieldValue.new(params[:admin_field_value])

    respond_to do |format|
      if @admin_field_value.save
        format.html { redirect_to @admin_field_value, notice: 'Field value was successfully created.' }
        format.json { render json: @admin_field_value, status: :created, location: @admin_field_value }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_field_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/field_values/1
  # PUT /admin/field_values/1.json
  def update
    @admin_field_value = Admin::FieldValue.find(params[:id])

    respond_to do |format|
      if @admin_field_value.update_attributes(params[:admin_field_value])
        format.html { redirect_to @admin_field_value, notice: 'Field value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_field_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/field_values/1
  # DELETE /admin/field_values/1.json
  def destroy
    @admin_field_value = Admin::FieldValue.find(params[:id])
    @admin_field_value.destroy

    respond_to do |format|
      format.html { redirect_to admin_field_values_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/field_values_helper.rb
module Admin::FieldValuesHelper
end

app/views/admin/field_values/_form.html.erb
<%= form_for(@admin_field_value) do |f| %>
  <% if @admin_field_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_field_value.errors.count, "error") %> prohibited this admin_field_value from being saved:</h2>

      <ul>
      <% @admin_field_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :field_id %><br />
    <%= f.number_field :field_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/field_values/edit.html.erb
<h1>Editing admin_field_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_field_value %> |
<%= link_to 'Back', admin_field_values_path %>

app/views/admin/field_values/index.html.erb
<h1>Listing admin_field_values</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Item</th>
    <th>Field</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_field_values.each do |admin_field_value| %>
  <tr>
    <td><%= admin_field_value.value %></td>
    <td><%= admin_field_value.item_id %></td>
    <td><%= admin_field_value.field_id %></td>
    <td><%= link_to 'Show', admin_field_value %></td>
    <td><%= link_to 'Edit', edit_admin_field_value_path(admin_field_value) %></td>
    <td><%= link_to 'Destroy', admin_field_value, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field value', new_admin_field_value_path %>

app/views/admin/field_values/new.html.erb
<h1>New admin_field_value</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_field_values_path %>

app/views/admin/field_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @admin_field_value.value %>
</p>

<p>
  <b>Item:</b>
  <%= @admin_field_value.item_id %>
</p>

<p>
  <b>Field:</b>
  <%= @admin_field_value.field_id %>
</p>


<%= link_to 'Edit', edit_admin_field_value_path(@admin_field_value) %> |
<%= link_to 'Back', admin_field_values_path %>