config/routes.rb
Pages::Application.routes.draw do

  namespace :admin do resources :field_values end

  devise_for :users

  

  namespace :admin do 
    
    
    match 'settings' => 'settings#categories'
    match 'settings/categories' => 'settings#categories'
    match 'settings/fields' => 'settings#fields'
    
    resources :field_types
    resources :assets, :only => [ :create, :destroy ]
    resources :themes, :only => [ :index, :show  ]
    resources :agencies
    resources :items
    resources :categories, :only => [ :new, :create, :destroy ]
    resources :fields
    resources :components, :except  => [ :index, :show ]
  end
  
  match '/admin' => 'admin/settings#fields'
  
  match ':permalink' => 'sites#show'
  
  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/agency.rb
class Admin::Agency < ActiveRecord::Base
  has_many :items
  has_many :categories
  has_many :fields, :through => :categories
  has_many :field_types
  
  liquid_methods :items, :name
end

app/models/admin/asset.rb
class Admin::Asset < ActiveRecord::Base
  mount_uploader :file, FileUploader
  
  belongs_to :theme
  
  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
      {
        "name" => read_attribute(:file),
        "size" => file.size,
        "url" => file.url,
        "thumbnail_url" => file.thumb.url,
        "asset_id" => id
      }
    end
end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  belongs_to :agency
  has_many :fields
  
  default_scope :order => 'label asc'
  
  scope :active, where(:active => true)
  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
  
end

app/models/admin/component.rb
class Admin::Component < ActiveRecord::Base
  attr_accessible :theme_id, :component_type_id, :content, :template_id, :title, :permalink
  
  # associations
  belongs_to :component_type
  belongs_to :template, :class_name => 'Component'
  belongs_to :theme
  
  # scopes
  scope :by_permalink, lambda { |permalink| where(:permalink => permalink) }
  scope :by_agency, lambda { |agency_id| where("admin_themes.agency_id" => agency_id).joins(:theme) }
  scope :template, where(:component_type_id => 1)
  scope :page, where(:component_type_id => 2)
  scope :stylesheet, where(:component_type_id => 3)
  scope :javascript, where(:component_type_id => 4)
  
  # liquid
  liquid_methods :title, :content, :permalink
end

app/models/admin/component_type.rb
class Admin::ComponentType < ActiveRecord::Base
  attr_accessible :label
  
  has_many :components
end

app/models/admin/field.rb
class Admin::Field < ActiveRecord::Base
  belongs_to :category
  belongs_to :field_type
    
  validates_presence_of :category, :field_type
    
  default_scope :order => 'label asc'
  
  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
end

app/models/admin/field_type.rb
class Admin::FieldType < ActiveRecord::Base
  attr_accessible :label
  belongs_to :agency  
  has_many :fields
  
  default_scope :order => 'label asc'
end

app/models/admin/field_value.rb
class Admin::FieldValue < ActiveRecord::Base
  attr_accessible :field_id, :item_id, :value
  
  belongs_to :item
  belongs_to :field
  
  delegate :field_type_id, :label, :category, :to => :field
  
  scope :find_by_item_and_field_ids, lambda { |item_id, field_id| where(:item_id => item_id, :field_id => field_id).pluck(:value).first}
end

app/models/admin/item.rb
class Admin::Item < ActiveRecord::Base
  belongs_to :agency
  has_many :field_values, :dependent => :destroy

  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
  
  liquid_methods :title, :description
    
  def field_values_attributes=(attributes)
    puts attributes.inspect()
  end
end

app/models/admin/theme.rb
class Admin::Theme < ActiveRecord::Base
  attr_accessible :agency_id, :title
  
  # associations
  belongs_to :agency
  has_many :assets
  has_many :templates,   :class_name => 'Component', :conditions => "component_type_id = 1"
  has_many :pages,       :class_name => 'Component', :conditions => "component_type_id = 2"
  has_many :stylesheets, :class_name => 'Component', :conditions => "component_type_id = 3"
  has_many :javascripts, :class_name => 'Component', :conditions => "component_type_id = 4"  
  has_many :assets  

  
  # scopes
  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController

  before_filter :authenticate_user!
  
  layout 'admin'
  
  def categories
    @categories = @current_agency.categories.active.includes(:fields)
  end
  
  def fields
    @categories = @current_agency.categories.active
    @fields = @categories.map{|c| c.fields}.flatten.sort{|x,y| x.label <=> y.label}
    @fieldtypes = @current_agency.field_types
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :current_agency
  
  # https://gist.github.com/999482
  # We don't want to render the layout if PJAX is working
  def render(options = nil, extra_options = {}, &block)
    if request.headers['X-PJAX'] == 'true'
      options = {} if options.nil?
      options[:layout] = false
    end
    super(options, extra_options, &block)
  end

  def prepare_sidebar
    @theme = Admin::Theme.find(session[:theme_id])
    @templates = @theme.templates
    @pages = @theme.pages
    @stylesheets = @theme.stylesheets
    @javascripts = @theme.javascripts
    @assets = @theme.assets
  end

  private

  def current_agency
    @current_agency = Admin::Agency.find_by_domain(request.host)
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  layout 'website'

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Admin::Component.page.by_agency(@current_agency.id).by_permalink(params[:permalink])[0]
    raise ActiveRecord::RecordNotFound, 'Page not found' if @page.nil?
    
    @agency = @current_agency
    
    respond_to do |format|
      format.html { render :layout => false}
      format.json { render json: @page }
    end
  end
end

app/helpers/admin/agencies_helper.rb
module Admin::AgenciesHelper
end

app/helpers/admin/assets_helper.rb
module Admin::AssetsHelper

end

app/helpers/admin/fields_helper.rb
module Admin::FieldsHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/admin/themes_helper.rb
module Admin::ThemesHelper
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def liquidize(content, arguments)
    Liquid::Template.parse(content).render(arguments)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_sidebar.html.erb
<div class="well" style="padding: 8px 0;">  
  <ul class="nav nav-list">
    <li class="nav-header">Settings</li>
    <li><%= link_to 'Fields', admin_settings_fields_url %></li>
    <li><%= link_to 'Categories', admin_settings_categories_url %></li>
  </ul>
</div>

app/views/admin/settings/categories.html.erb
<div class="span3">
  <%= render 'sidebar' %>
</div>
<div class="span9">
  <div class="block">
    <h1>
      Categories
      <%= link_to 'New Category', new_admin_category_url, 
          :class =>'btn btn-primary float-right new-button-category', 
          :'data-type' => 'html', 
          :remote => true %>
    </h1>
    <div id="new-form-container" style="display:none;"></div>
    <table class="table">
      <thead>
        <tr>
          <th>Label</th>
          <th>Fields</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="categories">
        <%= render @categories %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/settings/fields.html.erb
<div class="span3">
  <%= render 'sidebar' %>
</div>
<div class="span9">
  <div class="block">
    <h1>
      Fields
      <%= link_to 'New Field', new_admin_field_url, 
          :class =>'btn btn-primary float-right new-button-field', 
          :'data-type' => 'html', 
          :remote => true %>    
    </h1>
    <div id="new-form-container" style="display:none;"></div>
    <table class="table">
      <thead>
        <tr>
          <th>Label</th>
          <th>Category</th>
          <th>Type</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="fields">
        <%= render @fields %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/settings/index.html.erb
<% content_for :sidebar do %>
  <%= render 'sidebar' %>
<% end %>
<div class="block">
  <h1>
    Categories
    <button class="btn btn-primary float-right">New Category</button>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Label</th>
        <th>Fields</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.label %></td>
          <td>
            <%= category.fields.pluck(:label).join(', ') %>
          </td>
          <td><%= link_to 'Delete', category, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>